/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PillarDRouteImport } from './routes/pillar-d'
import { Route as PillarCRouteImport } from './routes/pillar-c'
import { Route as PillarBRouteImport } from './routes/pillar-b'
import { Route as PillarARouteImport } from './routes/pillar-a'
import { Route as FlywheelRouteImport } from './routes/flywheel'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarDRoute = PillarDRouteImport.update({
  id: '/pillar-d',
  path: '/pillar-d',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarCRoute = PillarCRouteImport.update({
  id: '/pillar-c',
  path: '/pillar-c',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarBRoute = PillarBRouteImport.update({
  id: '/pillar-b',
  path: '/pillar-b',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarARoute = PillarARouteImport.update({
  id: '/pillar-a',
  path: '/pillar-a',
  getParentRoute: () => rootRouteImport,
} as any)
const FlywheelRoute = FlywheelRouteImport.update({
  id: '/flywheel',
  path: '/flywheel',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/command-center': typeof CommandCenterRoute
  '/flywheel': typeof FlywheelRoute
  '/pillar-a': typeof PillarARoute
  '/pillar-b': typeof PillarBRoute
  '/pillar-c': typeof PillarCRoute
  '/pillar-d': typeof PillarDRoute
  '/radar': typeof RadarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/command-center': typeof CommandCenterRoute
  '/flywheel': typeof FlywheelRoute
  '/pillar-a': typeof PillarARoute
  '/pillar-b': typeof PillarBRoute
  '/pillar-c': typeof PillarCRoute
  '/pillar-d': typeof PillarDRoute
  '/radar': typeof RadarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/command-center': typeof CommandCenterRoute
  '/flywheel': typeof FlywheelRoute
  '/pillar-a': typeof PillarARoute
  '/pillar-b': typeof PillarBRoute
  '/pillar-c': typeof PillarCRoute
  '/pillar-d': typeof PillarDRoute
  '/radar': typeof RadarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/command-center'
    | '/flywheel'
    | '/pillar-a'
    | '/pillar-b'
    | '/pillar-c'
    | '/pillar-d'
    | '/radar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/command-center'
    | '/flywheel'
    | '/pillar-a'
    | '/pillar-b'
    | '/pillar-c'
    | '/pillar-d'
    | '/radar'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/command-center'
    | '/flywheel'
    | '/pillar-a'
    | '/pillar-b'
    | '/pillar-c'
    | '/pillar-d'
    | '/radar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CommandCenterRoute: typeof CommandCenterRoute
  FlywheelRoute: typeof FlywheelRoute
  PillarARoute: typeof PillarARoute
  PillarBRoute: typeof PillarBRoute
  PillarCRoute: typeof PillarCRoute
  PillarDRoute: typeof PillarDRoute
  RadarRoute: typeof RadarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar-d': {
      id: '/pillar-d'
      path: '/pillar-d'
      fullPath: '/pillar-d'
      preLoaderRoute: typeof PillarDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar-c': {
      id: '/pillar-c'
      path: '/pillar-c'
      fullPath: '/pillar-c'
      preLoaderRoute: typeof PillarCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar-b': {
      id: '/pillar-b'
      path: '/pillar-b'
      fullPath: '/pillar-b'
      preLoaderRoute: typeof PillarBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar-a': {
      id: '/pillar-a'
      path: '/pillar-a'
      fullPath: '/pillar-a'
      preLoaderRoute: typeof PillarARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flywheel': {
      id: '/flywheel'
      path: '/flywheel'
      fullPath: '/flywheel'
      preLoaderRoute: typeof FlywheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  CommandCenterRoute: CommandCenterRoute,
  FlywheelRoute: FlywheelRoute,
  PillarARoute: PillarARoute,
  PillarBRoute: PillarBRoute,
  PillarCRoute: PillarCRoute,
  PillarDRoute: PillarDRoute,
  RadarRoute: RadarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
